services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: openlearn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: openlearn_db
      POSTGRES_USER: openlearn_user
      POSTGRES_PASSWORD: openlearn_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - openlearn_network

  # Redis for Caching and Sessions
  redis:
    image: redis:7-alpine
    container_name: openlearn_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openlearn_network
    command: redis-server --appendonly yes --requirepass redis_password

  # pgAdmin for Database Management (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openlearn_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openlearn.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - openlearn_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  openlearn_network:
    driver: bridge
